# Generated by Django 2.2.15 on 2020-12-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0119_auto_20201225_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='tasks',
            field=models.ManyToManyField(help_text='The tasks this problem belongs with, as shown on the tasks page.', to='judge.ProblemTask', verbose_name='problem tasks'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='types',
            field=models.ManyToManyField(help_text="The type of problem, as shown on the problem's page.", to='judge.ProblemType', verbose_name='problem types'),
        ),
    ]
