# Generated by Django 2.2.15 on 2020-12-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0120_auto_20201225_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtask',
            name='authors',
            field=models.ManyToManyField(blank=True, help_text='These users will be able to edit the task, and be listed as authors.', related_name='authored_tasks', to='judge.Profile', verbose_name='creators'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tasks',
            field=models.ManyToManyField(help_text='The tasks this problem belongs with, as shown on the tasks page.', related_name='problems_in_task', to='judge.ProblemTask', verbose_name='problem tasks'),
        ),
    ]
