# Generated by Django 2.2.15 on 2020-12-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0122_problemtask_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='tasks',
        ),
        migrations.AddField(
            model_name='problemtask',
            name='problems',
            field=models.ManyToManyField(help_text='the problems this task has.', related_name='tasks_of_problem', to='judge.Problem', verbose_name='problem tasks'),
        ),
    ]
