# Generated by Django 2.2.15 on 2021-01-08 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0125_auto_20201225_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='achievement name')),
                ('desc', models.TextField(verbose_name='achievement description')),
                ('logo_override_image', models.CharField(blank=True, default='', help_text='this image will appear in the profile of those who completed the achievements.', max_length=150, verbose_name='achievement image')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='gacha_points',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name='AchievementObtained',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateObtained', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date when the Achievement was obtained')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='judge.Achievement', verbose_name='achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievementsobtained', to='judge.Profile', verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.ManyToManyField(through='judge.AchievementObtained', to='judge.Achievement'),
        ),
    ]
