# Generated by Django 2.2.15 on 2021-01-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0126_auto_20210108_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='quality',
            field=models.IntegerField(default=1, help_text='Qualitat del achievement. 1 es comú, 2 rar, 3 epic, 4 llegendari', verbose_name='achievement quality'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.FloatField(default=100, help_text='raresa del Achievement. Una raresa de 100 significa que apareixerà 1 de cada 100 tirades de gacha. Una raresa de 50 serà 1 de cada 50 tirades, etc.', verbose_name='rarity as 1/n'),
        ),
    ]
