# Generated by Django 2.2.15 on 2021-01-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0128_auto_20210108_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='achievement name'),
        ),
    ]
