# Generated by Django 2.2.15 on 2021-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0129_auto_20210108_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_icon',
            field=models.TextField(help_text='Your preferred icon for this web.', null=True, verbose_name='preferred icon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_theme',
            field=models.TextField(help_text='Your preferred theme for this web.', null=True, verbose_name='preferred theme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_color',
            field=models.TextField(help_text='background color of your name in the users list.', null=True, verbose_name='user color'),
        ),
    ]
