# Generated by Django 2.2.15 on 2021-01-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0130_auto_20210108_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.IntegerField(default=1, help_text="Categoria del Achievement. 1 es sticker. 2 icona, 3 color d'usuari i 4 tema", verbose_name='achievement category'),
        ),
    ]
