# Generated by Django 2.2.15 on 2021-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0131_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_font',
            field=models.TextField(help_text='Your preferred font for this web.', null=True, verbose_name='preferred font'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.IntegerField(default=1, help_text="Categoria del Achievement. 1 es sticker. 2 icona, 3 color d'usuari, 4 tema i 5 font", verbose_name='achievement category'),
        ),
    ]
