# Generated by Django 2.2.15 on 2024-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0133_auto_20221211_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_primera',
            field=models.BooleanField(default=False, help_text='Whether this contest is on Primera Divisió de la Lliga de FP de Programació.', verbose_name='primera divisio'),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_segona',
            field=models.BooleanField(default=False, help_text='Whether this contest is on Segona Divisió de la Lliga de FP de Programació.', verbose_name='segona divisio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gacha_points',
            field=models.FloatField(db_index=True, default=0, help_text='Els punts gacha que ha gastat un usuari. No els punts que te. Els punts disponibles es calculen dinamicament entre la resta dels seus punts totals i aquest valor. Per donar gachapoints a un alumne, restar aquest valor. Permet negatius'),
        ),
    ]
