# Generated by Django 2.2.15 on 2024-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0134_auto_20240820_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lliga_primera_points',
            field=models.FloatField(db_index=True, default=0, help_text='Punts en la primera divisio de la lliga actual'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lliga_segona_points',
            field=models.FloatField(db_index=True, default=0, help_text='Punts en la segona divisio de la lliga actual'),
        ),
    ]
