# Generated by Django 2.2.15 on 2026-02-23 23:56

from django.db import migrations, models
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0135_auto_20240820_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='sql_db',
            field=models.FileField(blank=True, help_text='SQLite database file for SQL checker problems (.db)', null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, verbose_name='SQL database file'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line'), ('sql', 'SQL checker')], default='linecount', max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line'), ('sql', 'SQL checker')], max_length=10, verbose_name='checker'),
        ),
    ]
