# Generated by Django 2.2.15 on 2026-08-15 19:52

from django.db import migrations, models
import judge.utils.submission_feedback


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0136_auto_20260223_2356'),
    ]

    operations = [
        # Note: NOT dropping the old 'extended_feedback' TextField here on purpose.
        # This migration only adds the new file-backed field; the old column is
        # backfilled from and left in place until a later, separately-confirmed
        # migration drops it (see 0138_remove_submissiontestcase_extended_feedback.py).
        migrations.AddField(
            model_name='submissiontestcase',
            name='extended_feedback_file',
            field=models.FileField(blank=True, null=True, storage=judge.utils.submission_feedback.SubmissionFeedbackStorage(), upload_to=judge.utils.submission_feedback.submission_feedback_file, verbose_name='extended judging feedback'),
        ),
    ]
