# Generated by Django 2.2.15 on 2026-08-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0137_submissiontestcase_extended_feedback_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissiontestcase',
            name='extended_feedback',
        ),
    ]
