# Generated by Django 2.2.15 on 2026-08-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0138_remove_submissiontestcase_extended_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='public visibility')),
                ('content', models.TextField(blank=True, help_text="Shown when no translation exists for the student's language.", verbose_name='guide content')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='judge.Problem', verbose_name='associated problem')),
            ],
            options={
                'verbose_name': 'guide',
                'verbose_name_plural': 'guides',
            },
        ),
        migrations.CreateModel(
            name='GuideTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language')),
                ('content', models.TextField(verbose_name='translated guide content')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_translations', to='judge.Problem', verbose_name='problem')),
            ],
            options={
                'verbose_name': 'guide translation',
                'verbose_name_plural': 'guide translations',
                'unique_together': {('problem', 'language')},
            },
        ),
    ]
