# Generated by Django 2.2.15 on 2026-08-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0139_add_problem_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidetranslation',
            name='runtime',
            field=models.ForeignKey(blank=True, help_text='Leave blank to match any programming language.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='judge.Language', verbose_name='programming language'),
        ),
        migrations.AlterField(
            model_name='guidetranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('ca', 'Catalan'), ('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('pt', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sr-latn', 'Serbian (Latin)'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], help_text='Leave blank to match any interface language.', max_length=7, verbose_name='language'),
        ),
        migrations.AlterUniqueTogether(
            name='guidetranslation',
            unique_together={('problem', 'language', 'runtime')},
        ),
    ]
