# Generated by Django 2.2.15 on 2026-08-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0141_sql_problem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sql_points',
            field=models.FloatField(db_index=True, default=0, help_text='Punts en problemes de la categoria SQL, separats dels punts de programacio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sql_problem_count',
            field=models.IntegerField(default=0, help_text='Nombre de problemes de la categoria SQL resolts'),
        ),
        migrations.AlterField(
            model_name='guidetranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English'), ('de', 'German'), ('zh-hans', 'Simplified Chinese')], help_text='Leave blank to match any interface language.', max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='problemtranslation',
            name='language',
            field=models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English'), ('de', 'German'), ('zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language'),
        ),
    ]
