# Generated by Django 2.2.15 on 2026-08-16 21:19

from django.db import migrations, models
import judge.models.problem_data
import judge.utils.problem_data


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0143_database_group_rename_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemdata',
            name='mongo_db',
            field=models.FileField(blank=True, help_text='JSON database file for Mongo checker problems (.json)', null=True, storage=judge.utils.problem_data.ProblemDataStorage(), upload_to=judge.models.problem_data.problem_directory_file, verbose_name='Mongo database file'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line'), ('sql', 'SQL checker'), ('mongo', 'Mongo checker')], default='linecount', max_length=10, verbose_name='checker'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='checker',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('rstripped', 'Compara contra fitxer'), ('sorted', 'Linea a Linea (només profes)'), ('identical', 'Programame-like'), ('linecount', 'Line-by-line'), ('sql', 'SQL checker'), ('mongo', 'Mongo checker')], max_length=10, verbose_name='checker'),
        ),
    ]
