# Generated by Django 2.2.15 on 2026-08-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0145_security_violation_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='institution name')),
                ('short_name', models.CharField(help_text='Displayed anywhere the full institution name would be too long', max_length=20, verbose_name='short name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='institutions/', verbose_name='institution image')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
            ],
            options={
                'verbose_name': 'institution',
                'verbose_name_plural': 'institutions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='The real institution this team belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='judge.Institution', verbose_name='institution'),
        ),
    ]
