# Generated by Django 2.2.15 on 2026-08-17 10:21

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    Institution = apps.get_model('judge', 'Institution')
    for institution in Institution.objects.all():
        base = slugify(institution.name) or 'institut'
        slug = base
        n = 2
        while Institution.objects.filter(slug=slug).exclude(pk=institution.pk).exists():
            slug = '%s-%d' % (base, n)
            n += 1
        institution.slug = slug
        institution.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0146_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='slug',
            field=models.SlugField(default='', help_text='Institution name shown in URL', max_length=128, verbose_name='institution slug'),
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
    ]
