# Generated by Django 2.2.15 on 2026-08-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0147_institution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='freeze_time',
            field=models.DateTimeField(blank=True, help_text='If set and in the past, the scoreboard stops updating for anyone who cannot edit this contest: submissions made at or after this time still show up as submitted, but never reveal whether they were correct, and never move anyone up or down the standings. Stays frozen until this field is cleared, regardless of the contest end time -- there is no automatic unfreeze.', null=True, verbose_name='freeze time'),
        ),
    ]
