# Generated by Django 2.2.15 on 2026-08-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0148_contest_freeze_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_daily_solve_bonus_date',
            field=models.DateField(blank=True, help_text="Madrid calendar date (Europe/Madrid) on which this user last collected the 'first new problem of the day' GachaPoints bonus. Solving before and after Madrid midnight counts as two different days on purpose.", null=True, verbose_name='last daily solve bonus date'),
        ),
        migrations.AddField(
            model_name='submission',
            name='daily_bonus_awarded',
            field=models.BooleanField(default=False, help_text='Whether this submission was the one that earned its author the "first new problem of the day" GachaPoints bonus -- shown once on this submission\'s page, not recomputed afterwards (e.g. on rejudge).', verbose_name='daily solve bonus awarded'),
        ),
    ]
