# Generated by Django 2.2.15 on 2026-08-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0149_daily_solve_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='use_group_names',
            field=models.BooleanField(default=False, help_text='If enabled, users must pick a group name the first time they join this contest, instead of being identified by their own username. The scoreboard shows the group name in place of the username. The name is set once, when the user first joins, and can never be changed afterwards -- not even by leaving and rejoining.', verbose_name='use group names'),
        ),
        migrations.AddField(
            model_name='contestparticipation',
            name='group_name',
            field=models.CharField(blank=True, default='', help_text='Custom name chosen by the user for this participation, when the contest requires group names instead of usernames (Contest.use_group_names). Set once, at join time, and never changed afterwards.', max_length=100, verbose_name='group name'),
        ),
    ]
