# Generated by Django 2.2.15 on 2026-08-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_contest_group_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='mega_fanfare',
            field=models.BooleanField(default=False, help_text='Marks this achievement for an even more over-the-top gacha reveal than a normal legendary (extra confetti, rubber duck parade, rainbow background, a celebration sound), and sends an email to the site admins (settings.ADMINS) every time a user obtains it.', verbose_name='mega fanfare'),
        ),
    ]
