# Generated by Django 2.2.15 on 2026-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_achievement_mega_fanfare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.IntegerField(choices=[(-1, 'GachaPoints bonus (internal)'), (1, 'sticker'), (2, 'icon'), (3, 'user color'), (4, 'theme'), (5, 'font')], default=1, help_text="Categoria del Achievement. 1 es sticker. 2 icona, 3 color d'usuari, 4 tema i 5 font", verbose_name='achievement category'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='logo_override_image',
            field=models.ImageField(blank=True, help_text='this image will appear in the profile of those who completed the achievements.', max_length=150, null=True, upload_to='achievements/', verbose_name='achievement image'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='quality',
            field=models.IntegerField(choices=[(1, 'common'), (2, 'rare'), (3, 'epic'), (4, 'legendary')], default=1, help_text='Qualitat del achievement. 1 es comú, 2 rar, 3 epic, 4 llegendari', verbose_name='achievement quality'),
        ),
    ]
