# Generated by Django 2.2.15 on 2026-08-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0152_achievement_permissions_and_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set automatically to whoever created this achievement. A student with limited access to the admin can only edit or delete achievements they created themselves; real admins can edit or delete any achievement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to='judge.Profile', verbose_name='created by'),
        ),
    ]
