# Generated by Django 2.2.15 on 2026-08-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0153_achievement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo_override_image',
            field=models.ImageField(blank=True, help_text='This image will replace the default site logo for users viewing the organization.', max_length=150, null=True, upload_to='organizations/', verbose_name='Logo override image'),
        ),
    ]
