# Generated by Django 2.2.15 on 2026-08-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('judge', '0154_organization_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English'), ('de', 'German'), ('zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language')),
                ('title', models.CharField(max_length=200, verbose_name='translated title')),
                ('content', models.TextField(blank=True, verbose_name='translated content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='flatpages.FlatPage', verbose_name='page')),
            ],
            options={
                'verbose_name': 'flat page translation',
                'verbose_name_plural': 'flat page translations',
                'unique_together': {('page', 'language')},
            },
        ),
        migrations.CreateModel(
            name='BlogPostTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English'), ('de', 'German'), ('zh-hans', 'Simplified Chinese')], max_length=7, verbose_name='language')),
                ('title', models.CharField(max_length=100, verbose_name='translated title')),
                ('content', models.TextField(verbose_name='translated content')),
                ('summary', models.TextField(blank=True, help_text='Leave blank to fall back to the translated content, same as the untranslated post.', verbose_name='translated summary')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='judge.BlogPost', verbose_name='post')),
            ],
            options={
                'verbose_name': 'blog post translation',
                'verbose_name_plural': 'blog post translations',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
